### PR TITLE
Fail on lint issues and fixup the ones that have crept in

### LINKED ISSUE #469: Linting issues are not failing the CI Builds
Lint failures [are occuring during CI Builds on master](https://travis-ci.org/improbable-eng/grpc-web/jobs/542169483#L5890); however travis is not reporting build failure :(

### PR DESCRIPTION
**Pull request by jonny-improbable**
fixes #469

### CODE REVIEW

File: lint-all.sh [hunk 1]
```diff
@@ -1,8 +1,9 @@
 #!/bin/bash
+
 set -e
 
 echo "Linting go sources"
-cd go && ./lint.sh && cd ..
+cd go && . ./lint.sh && cd ..
```
Comment (johanbrandhorst) [inline lint-all.sh]: This confuses me. Do we have to source the script to run it? Maybe we should rewrite the script?

**Comment by jonny-improbable** [comment]
If I don't source it, a non-zero exit code will be ignored. TBH my bash-fu
is pretty weak, but this worked so I was happy (:
